.TH FdF 1 "May 04, 2017" 42
.SH NAME
fdf \- projects image of a map provided in fdf format
.SH SYNOPSIS
.B fdf
<file>
.SH DESCRIPTION
.B fdf
graghically portrays a list of integers provided in a file.
.sp
    file must be space delimited and in the following formats:
    \fIint\fR \fIint\fR ...'\\n'
    \fIint\fR,\fI0x[A-F]\fR \fIint\fR \fIint\fR,\fI0x[a-f]\fR \fIint\fR,\fI0x[0-9]\fR ...'\\n'

